language: cpp
os: linux
dist: bionic
compiler: gcc
python: "3.7"
rvm: 2.2.0

notifications:
  email: false

before_install:
    # Print usefull information
    - echo $LANG
    - echo $LC_ALL
    - pwd
    - ls -al
    # Update cmake
    - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
    - echo "f3546812c11ce7f5d64dc132a566b749 *cmake-3.3.2-Linux-x86_64.tar.gz" > cmake_md5.txt
    - md5sum -c cmake_md5.txt
    - tar -xvf cmake-3.3.2-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.3.2-Linux-x86_64 cmake-install
    - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
    - chmod 777 linux.sh
    - ./linux.sh

install:
    
script:
    - echo "Nothing"

branches:
  only:
  - "/^Develop[.][a-zA-Z0-9]+/"
