language: cpp
os: linux
dist: bionic
compiler: gcc
python: "3.7"
rvm: 2.2.0

notifications:
  email: false

before_install:
    # Print usefull information
    - echo $LANG
    - echo $LC_ALL
    - pwd
    - ls -al
    # Update cmake
    - sudo apt-get install cmake3.18.3
    - chmod 777 linux.sh
    - ./linux.sh

install:
    
script:
    - echo "Nothing"

branches:
  only:
  - "/^Develop[.][a-zA-Z0-9]+/"
