name: Zinet Debug

on: 
  push:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
          name: "Windows Latest MSVC",
          os: windows-latest
        }

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install cmake
          cmake --version
      - name: Generate CMakeFiles
        shell: bash
        run: |
          python GenerateCMakeFiles.py
      - name: Build
        shell: cmd
        run: |
          mkdir build
          build_windows.bat
          MSBuild.exe build/Zinet.sln
  tests:
    name: ${{ matrix.config.name }}
    needs: build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
          name: "Windows Latest MSVC",
          os: windows-latest
        }
    
    steps:
      - name: Core Tests
        shell: bash
        run: |
          ls
          echo ---
          ls build
          echo ---
          ls build/runtime
          echo ---
          ls build/runtime/Debug
          echo ---
          ./build/runtime/Debug/ZtCoreTest.exe