name: CMake Build Matrix

on: 
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
          name: "Windows Latest MSVC",
          os: windows-latest,
          artifact: "windows_msvc.7z",
          build_type: "Release",
          cc: "cl",
          cxx: "cl",
          environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
          archiver: "7z a",
          generators: "Visual Studio 16 2019"
        }

  steps:
    - uses: actions/checkout@v
    
    - name: Install dependencies on windows
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install cmake
        cmake --version
    - name: Generate CMakeFiles
      shell: bash
      run: |
        python GenerateCMakeFiles.py
    - name: Build
      shell: bash
      run: |
        mkdir build
        build_windows.bat